### ISSUE TITLE
Jekyll enters infinite regenerate loop when using JAPR

### ISSUE THREAD

**Issue by steinsag** [janosrusiczki/japr#17]
I added JAPR to my project and it works fine generating a single JS and CSS file.

However, if I'm in Jekyll watch mode, the first change I do to any page, layout, include, etc. triggers an infinite loop regenerating everything. Does that work for anyone currently?

I'm using jekyll 2.5.2.

**Comment by greenify** [comment]
did you manage to find a fix for this?

**Comment by steinsag** [comment]
No, I found no work-around...

**Comment by davkal** [comment]
+1
