### ISSUE TITLE
Unable to activate

### ISSUE THREAD

**Issue by c-hris** [janosrusiczki/japr#19]
I get this error
`ise_if_conflicts': Unable to activate japr-0.3.2, because liquid-3.0.6 conflicts
 with liquid (~> 2.4), jekyll-3.0.0 conflicts with jekyll (~> 2.0) (Gem::LoadErr`

**Comment by c-hris** [comment]
Any suggestion

**Comment by c-hris** [comment]
Any suggestion

**Comment by guayom** [comment]
Same error
Unable to activate japr-0.3.2, because jekyll-3.0.1 conflicts with jekyll (~> 2.0), liquid-3.0.6 conflicts with liquid (~> 2.4) (Gem::ConflictError)

**Comment by owenrh** [comment]
Same error : (

> Unable to activate japr-0.3.2, because liquid-3.0.6 conflicts with liquid (~> 2.4), jekyll-3.1.2 conflicts with jekyll (~> 2.0)

**Comment by janosrusiczki** [comment]
Possibly solved by version 0.4 which was just released. Feedback would be appreciated.
