### ISSUE TITLE
Support Jekyll 3.x

### ISSUE THREAD

**Issue by zoni** [janosrusiczki/japr#20]
Jekyll 3.0.0 was released on 2015-10-26 and 3.1.0 has been released two days ago at the time of this writing (making it 2016-01-23) but japr locks itself to Jekyll 2.x at this time.

It would be nice if it could be updated and a new release made to support the latest version of Jekyll. Looking at [the changes](http://jekyllrb.com/docs/history/) it does not look like there would be significant API changes to adapt to.

**Comment by kitsched** [comment]
If you can build a stable gem locally, could you please create a PR?

**Comment by natecook1000** [comment]
The gem works fine with the [Jekyll and Liquid dependencies both bumped](https://github.com/natecook1000/japr/blob/nc-jekyll-3/japr.gemspec#L26-L27) up to `~> 3.0`. Is there a better way to write this? I can submit a PR, but would that require JAPR to bump to version 0.4.0?

**Comment by kitsched** [comment]
I will rebuild it if you submit the PR. Thanks.

**Comment by janosrusiczki** [comment]
Almost two years late, but version 0.4 was just released with updated support for Jekyll 3.5 and Liquid 4.0.
