### ISSUE TITLE
Getting Dependency error while running jekyll build

### ISSUE THREAD

**Issue by CaptainT33mo** [janosrusiczki/japr#40]
I followed all the steps in Getting Started Section from step 1 to 4 but as soon as I run the "**bundle exec jekyll build**" command from step 5 I get the below Dependency error.

`Dependency Error: Yikes! It looks like you don't have C:/Kommunicate.io/_plugins/japr.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- japr' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!`

If i run "**jekyll build**" alone I am getting this error:

```
WARN: Unresolved specs during Gem::Specification.reset:
      rb-fsevent (>= 0.9.4, ~> 0.9)
      ffi (< 2, >= 0.5.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:313:in `check_for_activated_spec!': You have already activated liquid 4.0.0, but
your Gemfile requires liquid 3.0.6. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:31:in `block in setup'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:26:in `map'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:26:in `setup'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.16.0/lib/bundler.rb:107:in `setup'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.6.2/exe/jekyll:11:in `<top (required)>'
        from C:/Ruby23-x64/bin/jekyll:22:in `load'
        from C:/Ruby23-x64/bin/jekyll:22:in `<main>'
```

Any solution for this?

**Comment by janosrusiczki** [comment]
Until I get the chance to look into this could you try installing https://github.com/matthodan/jekyll-asset-pipeline? It's the same thing under a different name.

**Comment by janosrusiczki** [comment]
Also could you share your Gemfile?

**Comment by CaptainT33mo** [comment]
Hi, I installed jekyll-asset-pipeline first but got the same error when I installed japr, and after the getting the same error I posted the issue on GitHub.

Here is my Gemfile: https://justpaste.it/6skyy

**Comment by janosrusiczki** [comment]
Please try with 'jekyll', '~> 3.5' in your Gemfile.

**Comment by CaptainT33mo** [comment]
I updated Jekyll to the latest version because Jekyll 3.5 was giving error. And after following from step 1 to 4 on jekyll 3.8.3 I got the following error.

`
bundle exec jekyll build
Configuration file: C:/my_site/_config.yml
  Dependency Error: Yikes! It looks like you don't have C:/my_site/_plugins/jekyll_asset_pipeline.rb or one of its dependencies installed. In order to
use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll_asset_pipeline' If
you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
                    ------------------------------------------------
      Jekyll 3.8.3   Please append `--trace` to the `build` command
                     for any additional information or backtrace.
                    ------------------------------------------------

C:\my_site>bundle exec jekyll build --trace
Configuration file: C:/my_site/_config.yml
  Dependency Error: Yikes! It looks like you don't have C:/my_site/_plugins/jekyll_asset_pipeline.rb or one of its dependencies installed. In order to
use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll_asset_pipeline' If
you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/external.rb:69:in `rescue in block in require_with_graceful_fail': C:/my_site/_plugins/jekyll_asset_pipeline.rb (Jekyll::Errors::MissingDependencyException)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/external.rb:57:in `block in require_with_graceful_fail'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/external.rb:56:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/external.rb:56:in `require_with_graceful_fail'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/plugin_manager.rb:87:in `block in require_plugin_files'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/plugin_manager.rb:85:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/plugin_manager.rb:85:in `require_plugin_files'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/plugin_manager.rb:21:in `conscientious_require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/site.rb:112:in `setup'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/site.rb:32:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/commands/build.rb:30:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/commands/build.rb:30:in `process'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-livereload-0.2.2/lib/jekyll-livereload/build.rb:30:in `process'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/command.rb:88:in `block in process_with_graceful_fail'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/command.rb:88:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/command.rb:88:in `process_with_graceful_fail'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/jekyll-76919eea3b3d/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bin/jekyll:22:in `load'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/bin/jekyll:22:in `<main>'
`

**Comment by janosrusiczki** [comment]
Unfortunately I cannot reproduce the problem to be able to debug.

**Comment by CaptainT33mo** [comment]
@janosrusiczki can you tell me which version of jekyll to use other that 3.4 and 3.5 . I will try to reproduce this with a new site.

**Comment by CaptainT33mo** [comment]
@janosrusiczki I found the solution. I added the below code to my Gemfile and it worked:
`group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
  gem "jekyll_asset_pipeline"
end`
Either I missed that somehow in your docs that `gem "jekyll_asset_pipeline"` needs to be added in the Gemfile at this place `group :jekyll_plugins do`  or you haven't added them in the docs.

**Comment by janosrusiczki** [comment]
@CaptainT33mo Sorry about that, it is indeed [the same](https://github.com/janosrusiczki/janosrusiczki/blob/master/Gemfile) on my personal site, I just forgot to update the docs.
